apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: project                 # Make sure this matches your active namespace
type: Opaque
stringData:                          
  # 1. Used by the MySQL database deployment
  MYSQL_ROOT_PASSWORD: "ahmed"      
  MYSQL_DATABASE: "project_db"       
  MYSQL_USER: "project_user"         
  MYSQL_PASSWORD: "project_password"

  # 2. Used by the Python backend (envFrom)
  DB_HOST: "db-svc" # This should match the service name of your MySQL deployment
  DB_USER: "project_user"
  DB_PASSWORD: "project_password"
  DB_NAME: "project_db"