apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: project-role-binding
  namespace: project
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: project-role
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: project
